force-app/main/default/objects/SQX_Nonconformance__c/SQX_Nonconformance__c.object-meta.xml
<CustomObject>
    <label>Nonconformance</label>
    <nameField>
        <label>Nonconformance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nonconformances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SQX_Nonconformance__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Desciption of the NonConformance</description>
    <label>Description</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SQX_Nonconformance__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>Priority of the NonConformance</description>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SQX_Nonconformance__c/fields/QMS_Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>QMS_Reference_Number__c</fullName>
    <description>Reference Number of the NonConformance</description>
    <label>QMS Reference Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SQX_Nonconformance__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>Title of the NonConformance</description>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SQX_CaseTriggerHandler.cls
public class SQX_CaseTriggerHandler {
    private static final String CASE_TYPE='Problem';
    private static final String CASE_STATUS_ESCALATED='Escalated';
    private static final String CASE_STATUS_NEW='NEW';
    private static Map<Id,SQX_Nonconformance__c> nonconformances=new Map<Id,SQX_Nonconformance__c>();
    private static List<case> updatesCases=new List<case>();
    private static List<PermissionSetAssignment> PermissionSets=[SELECT Id,PermissionSet.name FROM PermissionSetAssignment WHERE  PermissionSet.Name='Case_Admin' AND AssigneeId=:userInfo.getUserId()];
    
    
    // Create Nonconformance and update case if Criteria Matched during Insert Context
    public static void checkandCreateNonconformance(List<Case>cases){
        
        try{
            for(Case cs:cases){
                if(cs.Type==CASE_TYPE){
                    createNonconformance(cs);    
                }    
            }
            if(nonconformances.values().size()>0){
                Insert nonconformances.values();
                
                for(Case cs:cases)
                {
                    updatesCases.add(createCase(cs,CASE_STATUS_NEW));  
                }
                if(!updatesCases.isEmpty()){
                    Update updatesCases;
                }
                
            }
        }
        
        catch(Exception ex){
            // Should Log instead of Debugging
            system.debug(ex.getMessage()+' at update'+ex.getLineNumber());
        }
    }
    
    // Create Nonconformance and update case if Criteria Matched during Update Context
    public static void updateCaseIfUserHasPermissionSet(List<Case> cases){
        try{
            for(Case cs:cases)
            {
                
                if(PermissionSets.size()>0 && cs.SQX_NC_Reference__c==null && cs.type==CASE_TYPE)
                {
                    createNonconformance(cs);
                }
            }
            if(nonconformances.values().size()>0)
            {
                Insert nonconformances.values();
                for(Case cs:cases)
                {
                    updatesCases.add(createCase(cs,CASE_STATUS_ESCALATED));
                }
                
                if(!updatesCases.isEmpty()){
                    update updatesCases;
                }
            }
        }catch(Exception ex){
            // Should Log instead of Debugging
            system.debug(ex.getMessage()+' at update'+ex.getLineNumber());
        }
    }
    
    //Create NonConformance Record
    private static void createNonconformance(Case cs){
        SQX_Nonconformance__c nonconformance=new SQX_Nonconformance__c();
        nonconformance.Priority__c=cs.Priority;
        nonconformance.Title__c= cs.Subject;
        nonconformance.Description__c= cs.Description;
        nonconformance.QMS_Reference_Number__c =cs.CaseNumber;
        nonconformances.put(cs.Id,nonconformance);
    }
    
    //Creating case object
    private static Case createCase(Case cs,String status){
        return new Case(Id=cs.Id,SQX_NC_Reference__c=nonconformances.get(cs.Id).Id,Status=status);
    }
    
}